"use client";
import {useEffect,useState} from "react";
import {AdminPage} from "@/components/admin/AdminPage";
import {createRecord,listCollectionByField,updateRecord} from "@/lib/firestore";
import {ImageUploader} from "@/components/ui/ImageUploader";

const PAGES=[
 {key:"microgreens",label:"Microgreens",fields:[["eyebrow","Hero eyebrow"],["title","Hero heading"],["body","Hero description"],["imageUrl","Hero image URL"],["moodEyebrow","Shop by mood — eyebrow"],["moodTitle","Shop by mood — heading"],["everydayTitle","Everyday Greens — title"],["everydayText","Everyday Greens — description"],["colourTitle","Colourful Crunch — title"],["colourText","Colourful Crunch — description"],["chefTitle","Chef Favourites — title"],["chefText","Chef Favourites — description"]]},
 {key:"contact",label:"Contact",fields:[["eyebrow","Hero eyebrow"],["title","Hero heading"],["body","Hero description"],["callTitle","Call — title"],["callText","Call — display text"],["phone","Phone"],["emailTitle","Email — title"],["emailText","Email — display text"],["email","Email address"],["serviceTitle","Service — title"],["serviceText","Service — description"],["formIntro","Enquiry form introduction"]]},
] as const;
type PageKey=typeof PAGES[number]["key"];
type Page={id:string;pageKey:PageKey;status:"draft"|"published";[key:string]:unknown};
export default function Pages(){
 const[selected,setSelected]=useState<PageKey>(PAGES[0].key),[form,setForm]=useState<Page|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);const page=PAGES.find(p=>p.key===selected)!;
 async function load(){try{const r=await listCollectionByField<Page>("websitePages","pageKey",selected);setForm(r[0]??{id:"",pageKey:selected,status:"draft"});setError("")}catch{setError("Unable to load page.")}}
 useEffect(()=>{void load()},[selected]);
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setSaving(true);try{const {id:_id,...p0}=form;const p={...p0,pageKey:selected};if(form.id)await updateRecord("websitePages",form.id,p);else await createRecord("websitePages",p);await load()}catch{setError("Unable to save page.")}finally{setSaving(false)}}
 return <AdminPage><div className="container-fluid py-3"><h1 className="h3 seedlings-brand">Website Pages</h1><p className="text-muted">Choose a predefined website page. Page identity and route are read-only.</p>{error&&<div className="alert alert-danger">{error}</div>}<div className="row"><div className="col-lg-3 mb-3"><div className="list-group">{PAGES.map(p=><button type="button" key={p.key} className={"list-group-item list-group-item-action "+(selected===p.key?"active":"")} onClick={()=>setSelected(p.key)}>{p.label}</button>)}</div></div><div className="col-lg-9"><div className="card"><form onSubmit={save}><div className="card-body"><div className="alert alert-light border"><strong>{page.label}</strong><div className="small text-muted">Predefined website page • route cannot be changed</div></div>{page.fields.map(([key,label])=><div className="mb-3" key={key}>{key==="imageUrl"?<ImageUploader label={label} value={String(form?.[key]??"")} onChange={url=>setForm(f=>f&&({...f,[key]:url}))}/>:<><label className="form-label">{label}</label><textarea className="form-control" rows={key.includes("body")||key.includes("Text")||key.includes("Intro")?3:2} value={String(form?.[key]??"")} onChange={e=>setForm(f=>f&&({...f,[key]:e.target.value}))}/></>}</div>)}<hr/><h6>SEO</h6>{[["seoTitle","SEO title"],["seoDescription","SEO description"],["ogImageUrl","Open Graph image"]].map(([key,label])=><div className="mb-3" key={key}>{key==="ogImageUrl"?<ImageUploader label={label} value={String(form?.[key]??"")} onChange={url=>setForm(f=>f&&({...f,[key]:url}))}/>:<><label className="form-label">{label}</label>{key==="seoDescription"?<textarea className="form-control" rows={3} value={String(form?.[key]??"")} onChange={e=>setForm(f=>f&&({...f,[key]:e.target.value}))}/>:<input className="form-control" value={String(form?.[key]??"")} onChange={e=>setForm(f=>f&&({...f,[key]:e.target.value}))}/>}</>}</div>)}<label className="form-label">Status</label><select className="form-select" value={String(form?.status??"draft")} onChange={e=>setForm(f=>f&&({...f,status:e.target.value as "draft"|"published"}))}><option value="draft">Draft</option><option value="published">Published</option></select></div><div className="card-footer"><button className="btn btn-success" disabled={saving}>{saving?"Saving…":"Save Page"}</button></div></form></div></div></div></div></AdminPage>
}