"use client";
import {useEffect,useState} from "react";
import {AdminPage} from "@/components/admin/AdminPage";
import {createRecord,deleteRecord,listCollection,updateRecord} from "@/lib/firestore";
import type {Testimonial} from "@/types/cms";
type TestimonialForm={customerName:string;content:string;rating:number;status:Testimonial["status"]};
const empty:TestimonialForm={customerName:"",content:"",rating:0,status:"draft"};
export default function Page(){
 const [items,setItems]=useState<Testimonial[]>([]); const [form,setForm]=useState<TestimonialForm>(empty); const [editing,setEditing]=useState<string|null>(null); const [error,setError]=useState("");
 async function load(){try{setItems(await listCollection<Testimonial>("cmsTestimonials"));setError("")}catch{setError("Unable to load records.")}}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();try{if(editing)await updateRecord("cmsTestimonials",editing,form);else await createRecord("cmsTestimonials",form);setEditing(null);setForm(empty);await load()}catch{setError("Unable to save record.")}}
 return <AdminPage><div className="container-fluid py-3"><h1 className="h3 seedlings-brand">Testimonials</h1><p className="text-muted">Manage website content.</p>{error&&<div className="alert alert-danger">{error}</div>}<div className="row">
 <div className="col-xl-4 mb-3"><div className="card"><form onSubmit={save}><div className="card-body"><div className="mb-3"><label className="form-label">Customer Name</label><input className="form-control" type="text" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})} /></div><div className="mb-3"><label className="form-label">Content</label><textarea className="form-control" rows={4} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} /></div><div className="mb-3"><label className="form-label">Rating</label><input className="form-control" type="number" value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})} /></div><div className="mb-3"><label className="form-label">Status</label><select className="form-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Testimonial["status"]})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div></div><div className="card-footer"><button className="btn btn-success me-2">{editing?"Update":"Create"}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form></div></div>
 <div className="col-xl-8"><div className="card"><div className="card-body table-responsive p-0"><table className="table table-hover mb-0"><thead><tr><th>Customer Name</th><th>Content</th><th>Rating</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.customerName}</td><td>{item.content}</td><td>{item.rating}</td><td>{item.status}</td><td className="text-nowrap"><button className="btn btn-sm btn-outline-primary me-1" onClick={()=>{setEditing(item.id);setForm({customerName:item.customerName,content:item.content,rating:item.rating,status:item.status})}}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={async()=>{if(confirm("Delete this record?")){await deleteRecord("cmsTestimonials",item.id);await load()}}}>Delete</button></td></tr>)}{!items.length&&<tr><td colSpan={6} className="text-center text-muted py-4">No records yet.</td></tr>}</tbody></table></div></div></div>
 </div></div></AdminPage>
}
