"use client";
import {useEffect,useState} from "react";
import {AdminPage} from "@/components/admin/AdminPage";
import {createRecord,deleteRecord,listCollection,updateRecord} from "@/lib/firestore";
import type {Faq} from "@/types/cms";
type FaqForm={question:string;answer:string;status:Faq["status"];sortOrder:number};
const empty:FaqForm={question:"",answer:"",status:"draft",sortOrder:0};
export default function Page(){
 const [items,setItems]=useState<Faq[]>([]); const [form,setForm]=useState<FaqForm>(empty); const [editing,setEditing]=useState<string|null>(null); const [error,setError]=useState("");
 async function load(){try{setItems(await listCollection<Faq>("cmsFaq"));setError("")}catch{setError("Unable to load records.")}}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();try{if(editing)await updateRecord("cmsFaq",editing,form);else await createRecord("cmsFaq",form);setEditing(null);setForm(empty);await load()}catch{setError("Unable to save record.")}}
 return <AdminPage><div className="container-fluid py-3"><h1 className="h3 seedlings-brand">FAQ</h1><p className="text-muted">Manage website content.</p>{error&&<div className="alert alert-danger">{error}</div>}<div className="row">
 <div className="col-xl-4 mb-3"><div className="card"><form onSubmit={save}><div className="card-body"><div className="mb-3"><label className="form-label">Question</label><input className="form-control" type="text" value={form.question} onChange={e=>setForm({...form,question:e.target.value})} /></div><div className="mb-3"><label className="form-label">Answer</label><textarea className="form-control" rows={4} value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} /></div><div className="mb-3"><label className="form-label">Status</label><select className="form-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Faq["status"]})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div className="mb-3"><label className="form-label">Sort Order</label><input className="form-control" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})} /></div></div><div className="card-footer"><button className="btn btn-success me-2">{editing?"Update":"Create"}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form></div></div>
 <div className="col-xl-8"><div className="card"><div className="card-body table-responsive p-0"><table className="table table-hover mb-0"><thead><tr><th>Question</th><th>Answer</th><th>Status</th><th>Sort Order</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.question}</td><td>{item.answer}</td><td>{item.status}</td><td>{item.sortOrder}</td><td className="text-nowrap"><button className="btn btn-sm btn-outline-primary me-1" onClick={()=>{setEditing(item.id);setForm({question:item.question,answer:item.answer,status:item.status,sortOrder:item.sortOrder})}}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={async()=>{if(confirm("Delete this record?")){await deleteRecord("cmsFaq",item.id);await load()}}}>Delete</button></td></tr>)}{!items.length&&<tr><td colSpan={6} className="text-center text-muted py-4">No records yet.</td></tr>}</tbody></table></div></div></div>
 </div></div></AdminPage>
}
