"use client";

import {useEffect,useMemo,useState} from "react";
import {AdminPage} from "@/components/admin/AdminPage";
import {listCollection} from "@/lib/firestore";
import {createSubscriptionPlan,deleteSubscriptionPlan,updateSubscriptionPlan} from "@/lib/subscriptionPlanService";
import {createDeliveryCharge,deleteDeliveryCharge,updateDeliveryCharge} from "@/lib/deliveryChargeService";
import type {SubscriptionPlan,SubscriptionFrequency} from "@/types/subscriptionPlan";
import {SUBSCRIPTION_FREQUENCIES,subscriptionFrequencyLabel} from "@/types/subscriptionPlan";
import type {DeliveryCharge} from "@/types/deliveryCharge";
import {deliveryScopeLabel} from "@/types/deliveryCharge";

function money(v:number){return `₹${Number(v||0).toFixed(2)}`;}
const emptyPlan={name:"",frequency:"monthly" as SubscriptionFrequency,deliveriesPerTerm:4,price:0,deliveryChargeMode:"per_delivery" as const,deliveryCharge:0,active:true,description:""};
const emptyCharge={name:"",scope:"one_time_order" as const,mode:"flat" as const,amount:0,active:true,notes:""};

export default function SubscriptionMastersPage(){
 const[plans,setPlans]=useState<SubscriptionPlan[]>([]);const[charges,setCharges]=useState<DeliveryCharge[]>([]);
 const[tab,setTab]=useState<"plans"|"charges">("plans");const[editingPlan,setEditingPlan]=useState<SubscriptionPlan|null>(null);const[editingCharge,setEditingCharge]=useState<DeliveryCharge|null>(null);
 const[showPlan,setShowPlan]=useState(false);const[showCharge,setShowCharge]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 async function load(){setLoading(true);try{const[p,c]=await Promise.all([listCollection<SubscriptionPlan>("subscriptionPlans","updatedAt"),listCollection<DeliveryCharge>("deliveryCharges","updatedAt")]);setPlans(p);setCharges(c);setError("")}catch{setError("Unable to load subscription masters.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function togglePlan(x:SubscriptionPlan){try{await updateSubscriptionPlan(x.id,{active:!x.active});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update plan.")}}
 async function toggleCharge(x:DeliveryCharge){try{await updateDeliveryCharge(x.id,{active:!x.active});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update delivery charge.")}}
 async function removePlan(x:SubscriptionPlan){if(!confirm(`Delete ${x.name}?`))return;try{await deleteSubscriptionPlan(x.id);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete plan.")}}
 async function removeCharge(x:DeliveryCharge){if(!confirm(`Delete ${x.name}?`))return;try{await deleteDeliveryCharge(x.id);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete delivery charge.")}}
 return <AdminPage><div className="container-fluid py-3">
  <div className="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-3"><div><h1 className="h3 seedlings-brand mb-1">Subscription & Delivery Masters</h1><p className="text-muted mb-0">Define subscription plans and delivery charges before creating customer subscriptions or orders.</p></div><button className="btn btn-outline-secondary" onClick={()=>void load()}><i className="bi bi-arrow-clockwise"/></button></div>
  {error&&<div className="alert alert-danger">{error}</div>}
  <ul className="nav nav-tabs mb-3"><li className="nav-item"><button className={`nav-link ${tab==="plans"?"active":""}`} onClick={()=>setTab("plans")}><i className="bi bi-repeat me-1"/>Subscription Plans <span className="badge text-bg-secondary ms-1">{plans.length}</span></button></li><li className="nav-item"><button className={`nav-link ${tab==="charges"?"active":""}`} onClick={()=>setTab("charges")}><i className="bi bi-truck me-1"/>Delivery Charges <span className="badge text-bg-secondary ms-1">{charges.length}</span></button></li></ul>
  {tab==="plans"?<div className="card"><div className="card-header d-flex justify-content-between align-items-center"><div><strong>Subscription Plan Master</strong><div className="small text-muted">Monthly, Quarterly, Half-Yearly and Yearly plans.</div></div><button className="btn btn-success" onClick={()=>{setEditingPlan(null);setShowPlan(true)}}><i className="bi bi-plus-lg me-1"/>Add Plan</button></div>
   <div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead><tr><th>Plan</th><th>Frequency</th><th>Deliveries</th><th>Plan Price</th><th>Delivery</th><th>Customer pays / term</th><th>Status</th><th className="text-end">Actions</th></tr></thead><tbody>{plans.map(x=><tr key={x.id}><td><strong>{x.name}</strong><div className="small text-muted">{x.description||""}</div></td><td>{subscriptionFrequencyLabel(x.frequency)}</td><td>{x.deliveriesPerTerm}</td><td>{money(x.price)}</td><td>{x.deliveryChargeMode==="free"||x.deliveryChargeMode==="included"?"Free / Included":`${money(x.deliveryCharge)} / delivery`}</td><td>{money(x.price+(x.deliveryChargeMode==="per_delivery"?x.deliveryCharge*x.deliveriesPerTerm:0))}</td><td><span className={`badge text-bg-${x.active?"success":"secondary"}`}>{x.active?"Active":"Inactive"}</span></td><td className="text-end"><button className="btn btn-sm btn-outline-primary me-1" onClick={()=>{setEditingPlan(x);setShowPlan(true)}}>Edit</button><button className="btn btn-sm btn-outline-secondary me-1" onClick={()=>void togglePlan(x)}>{x.active?"Disable":"Enable"}</button><button className="btn btn-sm btn-outline-danger" onClick={()=>void removePlan(x)}>Delete</button></td></tr>)}{!plans.length&&!loading&&<tr><td colSpan={8} className="text-center text-muted py-5">No subscription plans defined.</td></tr>}</tbody></table></div>
  </div>:<div className="card"><div className="card-header d-flex justify-content-between align-items-center"><div><strong>Delivery Charges Master</strong><div className="small text-muted">Configure charges independently for one-time orders and subscriptions.</div></div><button className="btn btn-success" onClick={()=>{setEditingCharge(null);setShowCharge(true)}}><i className="bi bi-plus-lg me-1"/>Add Delivery Charge</button></div>
   <div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead><tr><th>Name</th><th>Applies to</th><th>Charge</th><th>Status</th><th>Notes</th><th className="text-end">Actions</th></tr></thead><tbody>{charges.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{deliveryScopeLabel(x.scope)}</td><td>{x.mode==="free"?"Free":`${money(x.amount)} / delivery`}</td><td><span className={`badge text-bg-${x.active?"success":"secondary"}`}>{x.active?"Active":"Inactive"}</span></td><td>{x.notes||"—"}</td><td className="text-end"><button className="btn btn-sm btn-outline-primary me-1" onClick={()=>{setEditingCharge(x);setShowCharge(true)}}>Edit</button><button className="btn btn-sm btn-outline-secondary me-1" onClick={()=>void toggleCharge(x)}>{x.active?"Disable":"Enable"}</button><button className="btn btn-sm btn-outline-danger" onClick={()=>void removeCharge(x)}>Delete</button></td></tr>)}{!charges.length&&!loading&&<tr><td colSpan={6} className="text-center text-muted py-5">No delivery charges defined.</td></tr>}</tbody></table></div>
  </div>}
  {showPlan&&<PlanModal value={editingPlan} onClose={()=>setShowPlan(false)} onSaved={async()=>{setShowPlan(false);await load()}} onError={setError}/>}
  {showCharge&&<ChargeModal value={editingCharge} onClose={()=>setShowCharge(false)} onSaved={async()=>{setShowCharge(false);await load()}} onError={setError}/>}
 </div></AdminPage>
}

function PlanModal({value,onClose,onSaved,onError}:{value:SubscriptionPlan|null;onClose:()=>void;onSaved:()=>Promise<void>;onError:(s:string)=>void}){
 const[v,setV]=useState(value?{...value}:emptyPlan);const[saving,setSaving]=useState(false);
 function freq(f:SubscriptionFrequency){setV(x=>({...x,frequency:f,deliveriesPerTerm:f==="monthly"?4:f==="quarterly"?12:f==="half_yearly"?24:48}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{if(value)await updateSubscriptionPlan(value.id,v);else await createSubscriptionPlan(v);await onSaved()}catch(e){onError(e instanceof Error?e.message:"Unable to save plan.")}finally{setSaving(false)}}
 return <Modal title={value?"Edit Subscription Plan":"Add Subscription Plan"} close={onClose}><form onSubmit={save}><div className="row g-3">
  <div className="col-md-6"><label className="form-label">Plan name *</label><input className="form-control" value={v.name} onChange={e=>setV({...v,name:e.target.value})} required/></div>
  <div className="col-md-6"><label className="form-label">Frequency *</label><select className="form-select" value={v.frequency} onChange={e=>freq(e.target.value as SubscriptionFrequency)}>{SUBSCRIPTION_FREQUENCIES.map(f=><option key={f} value={f}>{subscriptionFrequencyLabel(f)}</option>)}</select></div>
  <div className="col-md-6"><label className="form-label">Deliveries per term *</label><input className="form-control" type="number" min="1" value={v.deliveriesPerTerm} onChange={e=>setV({...v,deliveriesPerTerm:Number(e.target.value)})}/><div className="form-text">Defaults: Monthly 4, Quarterly 12, Half-Yearly 24, Yearly 48. Editable.</div></div>
  <div className="col-md-6"><label className="form-label">Plan price *</label><div className="input-group"><span className="input-group-text">₹</span><input className="form-control" type="number" min="0" step="0.01" value={v.price} onChange={e=>setV({...v,price:Number(e.target.value)})}/></div></div>
  <div className="col-md-6"><label className="form-label">Delivery pricing *</label><select className="form-select" value={v.deliveryChargeMode} onChange={e=>setV({...v,deliveryChargeMode:e.target.value as any})}><option value="included">Included in plan price</option><option value="per_delivery">Charge per delivery</option><option value="free">Free delivery</option></select></div>
  <div className="col-md-6"><label className="form-label">Delivery charge / delivery</label><div className="input-group"><span className="input-group-text">₹</span><input className="form-control" type="number" min="0" step="0.01" disabled={v.deliveryChargeMode!=="per_delivery"} value={v.deliveryCharge} onChange={e=>setV({...v,deliveryCharge:Number(e.target.value)})}/></div></div>
  <div className="col-12"><label className="form-label">Description</label><textarea className="form-control" rows={2} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></div>
  <div className="col-12"><div className="alert alert-light border mb-0">Customer total for this term: <strong>{money(v.price+(v.deliveryChargeMode==="per_delivery"?v.deliveryCharge*v.deliveriesPerTerm:0))}</strong></div></div>
 </div><div className="modal-footer px-0 pb-0 mt-3"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-success" disabled={saving}>{saving?"Saving...":"Save Plan"}</button></div></form></Modal>
}

function ChargeModal({value,onClose,onSaved,onError}:{value:DeliveryCharge|null;onClose:()=>void;onSaved:()=>Promise<void>;onError:(s:string)=>void}){
 const[v,setV]=useState(value?{...value}:emptyCharge);const[saving,setSaving]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{if(value)await updateDeliveryCharge(value.id,v);else await createDeliveryCharge(v);await onSaved()}catch(e){onError(e instanceof Error?e.message:"Unable to save delivery charge.")}finally{setSaving(false)}}
 return <Modal title={value?"Edit Delivery Charge":"Add Delivery Charge"} close={onClose}><form onSubmit={save}><div className="row g-3">
  <div className="col-md-6"><label className="form-label">Name *</label><input className="form-control" value={v.name} onChange={e=>setV({...v,name:e.target.value})} required placeholder="e.g. Standard Delivery"/></div>
  <div className="col-md-6"><label className="form-label">Applies to *</label><select className="form-select" value={v.scope} onChange={e=>setV({...v,scope:e.target.value as any})}><option value="one_time_order">One-time Order</option><option value="subscription">Subscription</option></select></div>
  <div className="col-md-6"><label className="form-label">Charge type</label><select className="form-select" value={v.mode} onChange={e=>setV({...v,mode:e.target.value as any})}><option value="flat">Fixed charge</option><option value="free">Free delivery</option></select></div>
  <div className="col-md-6"><label className="form-label">Amount</label><div className="input-group"><span className="input-group-text">₹</span><input className="form-control" type="number" min="0" step="0.01" disabled={v.mode==="free"} value={v.amount} onChange={e=>setV({...v,amount:Number(e.target.value)})}/></div><div className="form-text">For subscriptions, this is charged per delivery when selected.</div></div>
  <div className="col-12"><label className="form-label">Notes</label><textarea className="form-control" rows={2} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></div>
 </div><div className="modal-footer px-0 pb-0 mt-3"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-success" disabled={saving}>{saving?"Saving...":"Save Delivery Charge"}</button></div></form></Modal>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal d-block" role="dialog" aria-modal="true" tabIndex={-1}><div className="modal-dialog modal-lg modal-dialog-centered"><div className="modal-content"><div className="modal-header"><h2 className="modal-title h5 mb-0">{title}</h2><button className="btn-close" onClick={close} aria-label="Close"/></div><div className="modal-body">{children}</div></div></div></div>}
